### PR TITLE
🎨 ui(web): change avatar default color shade

### LINKED ISSUE #59: Color contrast of group colors is dull
image

Make the contrast same as other components

### PR DESCRIPTION
**Pull request by skushagra9**
## What does this PR do?

Fixes #59 

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

image

### CODE REVIEW

**Comment by McPizza0** [comment]
Please follow PR instructions: open an issue for this, include a screenshot

> If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists

> If a UI change was made: Added a screen recording or screenshots to this PR

**Comment by skushagra9** [comment]
ok

**Comment by McPizza0** [comment]
i think the contrast is a bit bad on light mode too
and maybe the font color on dark mode could be darker for more contrast?

**Comment by skushagra9** [comment]
Ok,

**Comment by skushagra9** [comment]
image

These are the same contrast as these

image

So should I make changes to both of them

**Comment by skushagra9** [comment]
Changes made :
image
image

**Review by McPizza0 — APPROVED** [review]
Looks good!

**Pull request merged**
