### PR TITLE
new profile created when user joins new org

### LINKED ISSUE #42: when a user creates or joins a new org, create new profile
I thought this was already implemented, but a user has a profile per organization
when creating a new org, or joining a new one as an existing user, we should duplicate their current profile and create a new one for the user

currently the users existing profile is used

### PR DESCRIPTION
**Pull request by skushagra9**
## What does this PR do?

Fixes #42 

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

### CODE REVIEW

**Comment by McPizza0** [comment]
@skushagra9 did you see the comments I left earlier?
they dont seem to be resolved

**Comment by skushagra9** [comment]
you are mentioning the comments on discord ??

**Review by McPizza0 — CHANGES_REQUESTED** [review]

**Comment by McPizza0** [comment]
sorry, forgot to request the changes

**Comment by skushagra9** [comment]
ok , got it

**Comment by skushagra9** [comment]
I did change the position of the newProfilePublicId , it was in else block earlier
Now its only declared once and can serve the statement

**Review by McPizza0 — APPROVED** [review]

**Pull request merged**
