### PR TITLE
Update README.md(added turbo in requirements, added copy commands for…

### PR DESCRIPTION
**Pull request by ErrolFernandes**
… local env variables)

### CODE REVIEW

**Review by McPizza0 — COMMENTED** [review]
Turbo was added as a repo dependency, shouldn't need to be installed globally. Did you have my issues with this?

**Comment by ErrolFernandes** [comment]
Yes, got an error as turbo was not a recognized command. got resolved after installing turbo.

**Comment by McPizza0** [comment]
Odd
let me try it out on a clean machine and check whats happening
I would rather not ask people to install something globally, especially since different versions could cause issues

**Comment by ErrolFernandes** [comment]
Sure. btw I was using windows.

**Comment by ErrolFernandes** [comment]
You're right! Should I remove it?

**Review by McPizza0 — APPROVED** [review]
Looks good!

**Comment by McPizza0** [comment]
hey @ErrolFernandes 

we have been strongly advised to add a contributor license agreement
motivation is to ensure that your contributions can only be "commercialized" or offered as a saas by the UnInbox team (Unproprietary Corporation) and not by others
please head over to https://cla-assistant.io/un/inbox and sign the agreement 
once we have more funds for legal stuff, we'll get a custom one built to add in clauses to the effect of "no changing to non-open licenses" etc.

thank you

**Pull request merged**
