### PR TITLE
✨ feat(landing-page):Update OSS-Friends Page

### LINKED ISSUE #72: Update landing site "OSS-Friends" page
File location: `apps/landing-page/pages/oss-friends.vue`

This page is part of a  Open Source projects network
The current page was made quite a while ago and never updated

The design of the page should be updated to use components from NuxtUi: https://ui.nuxt.com/getting-started
Heres some inspirations; https://documenso.com/oss-friends https://www.hanko.io/oss-friends https://infisical.com/infisical-friends

To get the data, we need to query the api located at `https://formbricks.com/api/oss-friends`

The link to the oss-page should be added to the `Footer` component

Finally, we should set the route rule to cache the page with a ttl of 24 hours (swr mode): https://nuxt.com/docs/guide/concepts/rendering#route-rules

### PR DESCRIPTION
**Pull request by skushagra9**
## What does this PR do?

Fixes #72 

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required
- [ ] Read [Contributing Guide](./CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

### CODE REVIEW

**Comment by skushagra9** [comment]
changed the design , now using NuxtUiComponents
image
image

**Comment by skushagra9** [comment]
Updated the footer
image

**Comment by skushagra9** [comment]
while fixing the cache, when I click on the footer, it doesn't takes me to the page, still the route updates

**Comment by skushagra9** [comment]
One more issue is there, when I route back to the landing page from the oss-friends page, the header works , but doesn't highlights components,

**Comment by McPizza0** [comment]
is the navigation issue still present @skushagra9

**Comment by skushagra9** [comment]
yes

**Review by McPizza0 — APPROVED** [review]

**Comment by skushagra9** [comment]
Thanks

**Pull request merged**
